name: CI

on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: install deps
        run: make setup
      - name: syntax check
        run: make lint
      - name: run test
        run: make test
